Passenger service
poramental/cab-aggregator-app pull request #1
Opened 2024-01-08 11:41 UTC by poramental

passenger-service

2024-01-08 12:48 UTC, AbandonedScope requested changes

2024-01-08 12:48 UTC, AbandonedScope commented on .idea/.gitignore
папки .idea не должно быть в гите

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/build.gradle
> +    implementation group: 'org.liquibase', name: 'liquibase-core', version: '4.25.1'
Выноси версии в properties

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/build.gradle
> +    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation
Удаляй комменты

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +@RequestMapping("/passengers")
Считается хорошей практикой версионированние API
Сделай api/v1/passengers

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    @GetMapping("/get-all")
Так неправильно именновать эндпоинты, из того, что это http метод get и так уже понятно, что ты будешь получать данный, поэтому из get-all можно убрать get
Дальше - т.к. когда ты будешь пытаться получить отдельного пассажира, ты будешь передавать id (/{id}), то эндпоинт на получение одного пассажира и многих уже будут отличаться, поэтому можно опустить и all
В итоге, запрос на получение всех пассажиров будет выглядеть как GET .../api/v1/passengers

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    @PostMapping("/add")
Тут тоже можно обойтись без /add, просто @PostMapping

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    @DeleteMapping("/delete-by-id")
Тут это тоже можно опустить, просто оставить @DeleteMapping("/{id}")

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Обычно такое не практикуют и удаляют только по id

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Тут тоже можно заменить /update-by-email на /{id}, по email обычно ничего не обновляют, ссылаются всё же по id-шке

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Это тоже не нужно

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Оставляй толко update по id

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Не нужно

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Не нужно

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Это обычно называют пагинацией и запрашивают страницу, поэтому эндпоинт может выглядеть просто как "/page", а лимит и смещение можно заменить на номер страницы и её размер, но тут смотри по желанию

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Сортировку можно совместить с запросом пагинации

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
не по email, только с id работаем

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Не нужно

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
просто "/{id}/rating"

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    }
Не нужно

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/dto/PassengerDto.java
> +    @NotBlank(message = "email should be not empty.")
Смотри, тут нужно реализоваь локализацию, т.к. это сообщение будет отправляться пользователю
Есть два подхода:
1. Локализовать на бэке(возвращать сразу сообщения на нужном языке) - тогда нужно использовать MessegeSource и читать эти сообщения из разных файлов локалей (английской, русской, французской и тд)
2. Локализовать на фронтэнде - мы просто возвращаем ключ, например, email.not-blank, а там они сами разберутся, какое сообщение и на каком языке им показывать пользователю
Я приму любой из этих вариантов, так что выбирай сам, как будешь реализовывать

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/dto/PassengerDto.java
> +    @NotBlank(message = "phone number should be not empty.")
Кстати, эти сообщения нужно было бы вынести в константы/читать из property файла

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new AppError(ex.getMessage()), HttpStatus.CONFLICT);
```suggestion
        return ResponseEntity.status(HttpStatus.CONFLICT)
                                           .body()(new AppError(ex.getMessage()));
```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(errors,HttpStatus.BAD_REQUEST);
```suggestion
        return ResponseEntity.badRequest()
                                           .body(errors).
```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new AppError(ex.getMessage()), HttpStatus.NOT_FOUND);
Тут тоже замени на использование статических методов класса ResponseEntity

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new AppError(ex.getMessage()),HttpStatus.BAD_REQUEST);
Тут тоже замени на использование статических методов класса `ResponseEntity`

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/PassengerAlreadyExistException.java
> +
Зачем так много пустых строк?

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/mappers/PassengerMapper.java
> +
```suggestion

```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/mappers/PassengerMapper.java
> +
```suggestion

```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/mappers/PassengerMapper.java
> +
```suggestion

```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +
```suggestion

```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +    }
Отсюда возвращай созданного пасажира

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +    }
Мы не возвращаем напрямую ResponseEntity, это класс, с которым работают непосредственно в контроллере

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        Optional<Passenger> passenger_opt = repositoryFunc.apply(passengerDtoGetter.get());
В Java переменный называют в camelcse, а не в snakecase

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +                String.format("passenger with username: %s is not found.", passengerDto.getUsername())
Прикольный подход, но в нашем случае не нужно обновлять пользователя по всем этим поля, только по id
Ты можешь использовать что-то подобное, чтобы просто получать пассажира по разным полям(например если будет эндпоинт для получения пассажира по email/phane и тд)

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        Optional<Passenger> passenger_opt = repositoryFunc.apply(passengerDtoGetter.get());
Если сделать так, то тот некрасивый if перестанет быть нужным
```suggestion
        Passenger passenger_opt = repositoryFunc.apply(passengerDtoGetter.get())
                                                .orElseThrow( () -> new PassengerNotFoundException(exceptionMessage));
```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        }else throw new PassengerNotFoundException(exceptionMessage);
На будущее, пиши так
```suggestion
        } else  {
           throw new PassengerNotFoundException(exceptionMessage);
        }
```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        else throw new PassengerNotFoundException(exceptionMessage);
```suggestion
        Passenger passenger = repositoryFunc.apply(param)
        .orElseThrow( () -> new PassengerNotFoundException(exceptionMessage));
        
         passengerRepository.delete(passenger);
         return HttpStatus.OK;
```

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +    private <T> HttpStatus  delete(T param,
Тут возвращай удалённую сущность

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        Optional<Passenger> passenger_opt = repositoryFunc.apply(param);
Вообще, лучше просто проверять, что пассажир по заданному id(ну или другому уникальному полю) существует, а не доставать его, так код более оптимальный

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        Optional<Passenger> passenger_opt = passengerRepository.findByPhone(passengerDto.getPhone());
Можно просто написать метод репозитория ... .existsByPhone/Email/Username/Id(...)

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        Optional<Passenger> passenger_opt = passengerRepository.findByEmail(passengerDto.getEmail());
Можно просто написать метод репозитория ... .existsByPhone/Email/Username/Id(...)

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        Optional<Passenger> passenger_opt = passengerRepository.findByUsername(passengerDto.getUsername());
Можно просто написать метод репозитория ... .existsByPhone/Email/Username/Id(...)

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +            case "name" ->
Можешь вынести в константы

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +    public ResponseEntity<List<PassengerDto>> getSortedListOfPassengers(String type) throws SortTypeException {
Возвращай дто, а не сразу ResponseEntity

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +                    passengerDto.getEmail()));
Да, скобки можно опускать, но в java принято всё же оборачивать if-ы в фигурные скобки

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        if(rating > 5 || rating < 0) throw new RatingException("invalid rating.");
Фигурные скобки, новая строка

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +        Optional<Passenger> passenger_opt = repositoryFunc.apply(param);
.orElseThrow...

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerService.java
> +    private <T> HttpStatus  addRating(int rating,
Не статус, а дто

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/resources/db/changelog/changeset/create-passenger-table.yaml
имхо, xml более читаемый

2024-01-08 12:48 UTC, AbandonedScope commented on passenger-service/src/main/resources/db/changelog/changeset/create-passenger-table.yaml
Хорошей практикой считается разнесение changeSet-тов по отдельным файлам
Вообще, переделай согласно [этому видео](https://www.youtube.com/watch?v=JTdcd4DYgEI&t=2015s&ab_channel=TheUsharik) (можешь писать в формате yaml, но структура должна быть похожей на ту, что в видео, так же, можешь sql инструкции писать напрямую в changeSet-ах, а не как в видео, разнося в отдельные файлы, тут на твоё усмотрение оставляю)

2024-01-10 07:51 UTC, AbandonedScope requested changes

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/dto/PassengerReqDto.java
> +public class PassengerReqDto {
Смотри, здесь или PassengerRequest, или PassengerDto, но не одновременно, выбери, что больше нравиться, и именуй в таком формате везде, +, если Request/Response будешь использовать, то можно разнести их по разным пакетам  ....dto.request и ....dto.response

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
>      @PostMapping("")
```suggestion
    @PostMapping
```

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
>      @GetMapping("")
```suggestion
    @GetMapping
```

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND)
Тут возвращай BadRequest

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/GlobalExceptionHandler.java
Вообще, можно объединить обработчики, которые возвращают один status code, просто в аннотации @ExceptionHandler пропиши несколько исключений, которые обрабатывает метод, а параметром метода сделай RuntimeException

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/PaginationFormatException.java
> +public class PaginationFormatException extends Exception{
RuntimeException

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/exceptions/PassengerAlreadyExistException.java
>  public class PassengerAlreadyExistException extends Exception{
RuntimeException

2024-01-10 07:51 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/mappers/PassengerMapper.java
> +    public PassengerRespDto entityToRespDto(Passenger passenger){
Не забудь здесь переименовать после того, как изменишь формат названия дто-шек

2024-01-12 08:16 UTC, AbandonedScope requested changes

2024-01-12 08:16 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    @GetMapping()
```suggestion
    @GetMapping
```

2024-01-12 08:16 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    @PostMapping()
```suggestion
    @PostMapping
```

2024-01-12 08:16 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +        return ResponseEntity.ok(passengerService.deletePassengerById(passengerId));
Тут возвращай статус NO_CONTENT

2024-01-12 08:16 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/dto/PassengerRequest.java
> +    @Pattern(regexp = ValidationFormat.PHONE_REGEX, message = "{phone.invalid.message}")
Зачем в {phone.invalid.message} фигурные скобки?

2024-01-12 08:16 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +                .orElseThrow(()-> new PassengerNotFoundException(String
passengerRepository.findById(passengerId).orElseThrow(...) - вынеси в отдельный метод, можешь назвать по типу getOrThrow...

2024-01-12 08:16 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/interfaces/PassengerService.java
> +            throws PassengerNotFoundException;
Зачем здесь throws? Если это RuntimeException, то throws не нужно

2024-01-15 07:57 UTC, AbandonedScope requested changes

2024-01-15 07:57 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +    public ResponseEntity<List<PassengerResponse>> getAll(){
Смотри, не возвращай просто List<...> чего-то, лучше будет возвращать объект дто, т.к. в будущем может быть необходимость добавить ещё то-нибудь в ответ(какие-нибудь метаданные например) и с дто это будет сделать гораздо проще, + фронту удобнее работать с объектами а не списками

2024-01-15 07:57 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/controllers/PassengerController.java
> +        return ResponseEntity.ok(passengerService.addPassenger(passengerDto));
Тут правильнее будет возвращать статус код CREATED

2024-01-15 07:57 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        checkUsernameExist(passengerDto);
Эти три метода вызываются в одном месте и каждый из них делает запрос в базу данных, придумай, как уменьшить кол-во запросов с 3-х до 1

2024-01-15 07:57 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        ));
Разнеси это на переменные, чтобы код был более понятным

2024-01-15 07:57 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        }
Тут это можно немного оптимизировать
Смотри, в Stream API есть метод `filter(...)`
Я предлагаю после `.map(Field::getName)` добавить что-то вроде `filter(field -> orderBy.equals(field))`, тогда, у нас в список попадут только те поля(одно поле), имена которых совпадает с `orderBy`
В Stream API также есть метод `findFirst()`, который возвращает `Optional`, содержащий первый найденный элемент
Т.к. это `Optional`, у него есть метод `orElseThrow(...)`, где ты можешь вызвать 
`new SortTypeException(ExceptionMessages.INVALID_TYPE_OF_SORT)`

2024-01-15 07:57 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
Посмотри форматирование в этом файле
В некоторых местах есть пустые строки, где они не нужны
Также добавь пробелы между 'if' и '(' там, где их нет
Посмотри перенос на новую строку, в некоторых местах он не нужен (например, ты перенёс вызов метода formatted у String) или наоборот нужен (например, мы переносим .orElseThrow на новую строку(именно вызов метода, а не лямбду, передаваемую в него))

2024-01-15 18:22 UTC, poramental commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        checkUsernameExist(passengerDto);
не знаю как это можно реализовать, тк если я объединю в один sql запрос(вида existAllByPhoneOrEmailOrUsername), то я не смогу сообщать пользователю в ошибке какой именно параметр занят.

2024-01-15 18:28 UTC, poramental commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        checkUsernameExist(passengerDto);
есть только идея сделать метод в passengerRepository который будет селектить из базы пользователей по всем параметрам одновременно, а потом если резалт лист будет пустой - допускать, а если нет, то пробегать по нему и сравнивать каждый параметр сущностей из этого листа с прилетающей дтошкой.  Но это выглядит как костыль.

2024-01-15 23:46 UTC, AbandonedScope requested changes

2024-01-15 23:46 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/dto/PassengerResponseList.java
> +public class PassengerResponseList {
Переименуй в PassengerListResponse

2024-01-15 23:46 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        if(passengerRepository.existsByPhone(passengerDto.getPhone())){
```suggestion
        if (passengerRepository.existsByPhone(passengerDto.getPhone())) {
```

2024-01-15 23:46 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        if (passengerRepository.existsByEmail(passengerDto.getEmail())){
```suggestion
        if (passengerRepository.existsByEmail(passengerDto.getEmail())) {
```

2024-01-15 23:46 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        if (passengerRepository.existsByUsername(passengerDto.getUsername())){
```suggestion
        if (passengerRepository.existsByUsername(passengerDto.getUsername())) {
```

2024-01-15 23:46 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        checkUsernameExist(passengerDto);
Сорри, что-то напутал
Здесь всё ок

2024-01-15 23:46 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +        if(rating > 5 || rating < 0) {
```suggestion
        if (rating > 5 || rating < 0) {
```

2024-01-18 07:57 UTC, AbandonedScope approved these changes

2024-01-18 07:57 UTC, AbandonedScope commented on passenger-service/src/main/java/com/modsen/passengerservice/services/PassengerServiceImpl.java
> +                .orElseThrow(() -> new SortTypeException(ExceptionMessages.INVALID_TYPE_OF_SORT));
```suggestion
       Arrays.stream(PassengerResponse.class.getDeclaredFields())
                .map(Field::getName)
                .filter(orderBy::equals)
                .findFirst()
                .orElseThrow(() -> new SortTypeException(ExceptionMessages.INVALID_TYPE_OF_SORT));
```

2024-01-18 13:07 UTC, merged